# Generated by Django 5.2.9 on 2025-12-15 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên thể loại')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tên sách')),
                ('author', models.CharField(max_length=100, verbose_name='Tác giả')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='Mã ISBN')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng tổng')),
                ('available_copies', models.PositiveIntegerField(default=1, verbose_name='Sẵn có')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='Thể loại')),
            ],
        ),
    ]
