# Generated by Django 5.2.9 on 2026-01-02 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'AUTHOR',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'BOOK',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'CATEGORIES',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LibraryUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'USERS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisher_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'PUBLISHER',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, to='app.author')),
                ('book', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, to='app.book')),
            ],
            options={
                'db_table': 'BOOK_AUTHOR',
                'managed': True,
                'unique_together': {('book', 'author')},
            },
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(through='app.BookAuthor', to='app.author'),
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('borrow_id', models.AutoField(primary_key=True, serialize=False)),
                ('borrow_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('book', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, to='app.book')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='app.libraryuser')),
            ],
            options={
                'db_table': 'BORROW_RECORDS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BorrowHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('returned_at', models.DateField()),
                ('days_late', models.IntegerField()),
                ('fine', models.IntegerField()),
                ('borrow', models.ForeignKey(db_column='borrow_id', on_delete=django.db.models.deletion.CASCADE, to='app.borrowrecord')),
            ],
            options={
                'db_table': 'BORROW_HISTORY',
            },
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, to='app.book')),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
            options={
                'db_table': 'BOOK_CATEGORY',
                'managed': True,
                'unique_together': {('book', 'category')},
            },
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(through='app.BookCategory', to='app.category'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(db_column='publisher_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.publisher'),
        ),
    ]
