# Generated by Django 5.2.9 on 2026-01-03 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_notification_review_borrowrecord_notified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'managed': True},
        ),
    ]
