# Generated by Django 5.2.9 on 2026-01-03 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_review_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'managed': True},
        ),
    ]
