# Generated by Django 5.2.9 on 2026-01-03 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_review_alter_notification_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
