# Generated by Django 5.2.9 on 2026-01-05 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_notification_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='bookauthor',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='bookcategory',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='borrowhistory',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='borrowrecord',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='libraryuser',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'managed': False},
        ),
    ]
