# Generated by Django 5.2.9 on 2026-01-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('requested_at', models.DateTimeField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=20)),
            ],
            options={
                'db_table': 'PAYMENT_REQUESTS',
                'managed': False,
            },
        ),
    ]
